---
title: "Example R markdown"
author: "Sviatoslav Sidorov"
date: "`r format(Sys.time(), '%d %B %Y')`"
output:
   html_document:
     code_folding: hide
     collapsed: no
     fig_align: center
     fig_caption: yes
     highlight: haddock
     keep_md: yes
     number_sections: yes
     smooth_scroll: no
     toc: yes
     toc_depth: 3
     toc_float: yes
---

```{r, include=T}
library(dplyr)
library(ggplot2)
```

Read args and create output paths:

```{r, include=T}
args = commandArgs()

input.name = args[9]

output.name = paste0(sub('\\.tsv', '', input.name), "_processed.tsv")

tsv.dir = "tsv"
dir.create(file.path(".", tsv.dir))

pdf.dir = "pdf"
dir.create(file.path(".", pdf.dir))
```
Read the input dataframe:

```{r, include=T}
df = read.table(file = input.name,
                sep = "\t",
                quote = "\"",
                header = F)

names(df) = c("number", "percentage", "category")
```

Output the processed dataframe in TSV:

```{r, include=T}
write.table(df %>% dplyr::select(category, number, percentage),
            file = file.path(tsv.dir, output.name),
            sep = "\t",
            quote = F,
            row.names = F)
```

Plot the percentages of mapped reads:

```{r, include=T}
p = df %>% 
    dplyr::filter(!is.na(percentage)) %>%
    ggplot() +
        geom_col(aes(x = category,
                     y = percentage,
                     fill = category)) +
        theme_classic() + 
        theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5))

p
```

Save the plot in PDF:

```{r, include=T}
ggsave(filename = file.path("pdf", "bowtie2_log_barplot.pdf"),
       plot = p)
```
